<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Gallery extends \Entities\Gallery implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Entities\\Gallery' . "\0" . 'imageId', '' . "\0" . 'Entities\\Gallery' . "\0" . 'memberId', '' . "\0" . 'Entities\\Gallery' . "\0" . 'bigUrl', '' . "\0" . 'Entities\\Gallery' . "\0" . 'thumbUrl', '' . "\0" . 'Entities\\Gallery' . "\0" . 'submitDate', '' . "\0" . 'Entities\\Gallery' . "\0" . 'imageDesc');
        }

        return array('__isInitialized__', '' . "\0" . 'Entities\\Gallery' . "\0" . 'imageId', '' . "\0" . 'Entities\\Gallery' . "\0" . 'memberId', '' . "\0" . 'Entities\\Gallery' . "\0" . 'bigUrl', '' . "\0" . 'Entities\\Gallery' . "\0" . 'thumbUrl', '' . "\0" . 'Entities\\Gallery' . "\0" . 'submitDate', '' . "\0" . 'Entities\\Gallery' . "\0" . 'imageDesc');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Gallery $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getImageId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getImageId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageId', array());

        return parent::getImageId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberId($memberId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberId', array($memberId));

        return parent::setMemberId($memberId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberId', array());

        return parent::getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBigUrl($bigUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBigUrl', array($bigUrl));

        return parent::setBigUrl($bigUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getBigUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBigUrl', array());

        return parent::getBigUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setThumbUrl($thumbUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThumbUrl', array($thumbUrl));

        return parent::setThumbUrl($thumbUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getThumbUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThumbUrl', array());

        return parent::getThumbUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubmitDate($submitDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubmitDate', array($submitDate));

        return parent::setSubmitDate($submitDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubmitDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubmitDate', array());

        return parent::getSubmitDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageDesc($imageDesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageDesc', array($imageDesc));

        return parent::setImageDesc($imageDesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageDesc', array());

        return parent::getImageDesc();
    }

}
