<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Rsvp extends \Entities\Rsvp implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Entities\\Rsvp' . "\0" . 'id', '' . "\0" . 'Entities\\Rsvp' . "\0" . 'memberId', '' . "\0" . 'Entities\\Rsvp' . "\0" . 'eventId', '' . "\0" . 'Entities\\Rsvp' . "\0" . 'rsvp', '' . "\0" . 'Entities\\Rsvp' . "\0" . 'responseDate');
        }

        return array('__isInitialized__', '' . "\0" . 'Entities\\Rsvp' . "\0" . 'id', '' . "\0" . 'Entities\\Rsvp' . "\0" . 'memberId', '' . "\0" . 'Entities\\Rsvp' . "\0" . 'eventId', '' . "\0" . 'Entities\\Rsvp' . "\0" . 'rsvp', '' . "\0" . 'Entities\\Rsvp' . "\0" . 'responseDate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Rsvp $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberId($memberId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberId', array($memberId));

        return parent::setMemberId($memberId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberId', array());

        return parent::getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventId($eventId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventId', array($eventId));

        return parent::setEventId($eventId);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventId', array());

        return parent::getEventId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRsvp($rsvp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRsvp', array($rsvp));

        return parent::setRsvp($rsvp);
    }

    /**
     * {@inheritDoc}
     */
    public function getRsvp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRsvp', array());

        return parent::getRsvp();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponseDate($responseDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponseDate', array($responseDate));

        return parent::setResponseDate($responseDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponseDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponseDate', array());

        return parent::getResponseDate();
    }

}
